name: Run Rest-Assured Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Maven
        run: sudo apt-get install maven -y

      - name: Print Current Directory
        run: pwd

      - name: Build and Test
        run: mvn clean test
        working-directory: /home/runner/work/Rest-Assured/RestAssignent 1

      - name: Archive Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports
